# Leitura de chave inexistente 
BACKUP
READ [c1]
# Criação e escrita de 2 chaves 
WRITE [(c1,v1)(chave2,valor-exemplo)]
BACKUP
# Leitura de chave existente 
READ [chave2]
# Escrita de uma chave nova e outra existente 
WRITE [(chave2,valor-exemplo2)(umaChave,umValor)]
# Eliminação de chave existente e de chave não existente 
BACKUP
DELETE [c1,chaveAleatoria]
# Espera de um segundo 
# backup 
BACKUP
BACKUP
BACKUP
# Impressão de toda a tabela 
SHOW
